/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ProductDTO } from './ProductDTO';
import {
    ProductDTOFromJSON,
    ProductDTOFromJSONTyped,
    ProductDTOToJSON,
} from './ProductDTO';

/**
 * 
 * @export
 * @interface CartProductDTO
 */
export interface CartProductDTO {
    /**
     * 
     * @type {string}
     * @memberof CartProductDTO
     */
    id?: string;
    /**
     * 
     * @type {ProductDTO}
     * @memberof CartProductDTO
     */
    product?: ProductDTO;
}

/**
 * Check if a given object implements the CartProductDTO interface.
 */
export function instanceOfCartProductDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function CartProductDTOFromJSON(json: any): CartProductDTO {
    return CartProductDTOFromJSONTyped(json, false);
}

export function CartProductDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CartProductDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'product': !exists(json, 'product') ? undefined : ProductDTOFromJSON(json['product']),
    };
}

export function CartProductDTOToJSON(value?: CartProductDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'product': ProductDTOToJSON(value.product),
    };
}

