/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';
import type { FormDTO } from './FormDTO';
import {
    FormDTOFromJSON,
    FormDTOFromJSONTyped,
    FormDTOToJSON,
} from './FormDTO';

/**
 * 
 * @export
 * @interface FormDTORequestResponse
 */
export interface FormDTORequestResponse {
    /**
     * 
     * @type {FormDTO}
     * @memberof FormDTORequestResponse
     */
    response?: FormDTO;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof FormDTORequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the FormDTORequestResponse interface.
 */
export function instanceOfFormDTORequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function FormDTORequestResponseFromJSON(json: any): FormDTORequestResponse {
    return FormDTORequestResponseFromJSONTyped(json, false);
}

export function FormDTORequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FormDTORequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : FormDTOFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function FormDTORequestResponseToJSON(value?: FormDTORequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': FormDTOToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

