/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { OrderStatusEnum } from './OrderStatusEnum';
import {
    OrderStatusEnumFromJSON,
    OrderStatusEnumFromJSONTyped,
    OrderStatusEnumToJSON,
} from './OrderStatusEnum';

/**
 * 
 * @export
 * @interface OrderUpdateDTO
 */
export interface OrderUpdateDTO {
    /**
     * 
     * @type {string}
     * @memberof OrderUpdateDTO
     */
    id?: string;
    /**
     * 
     * @type {OrderStatusEnum}
     * @memberof OrderUpdateDTO
     */
    status?: OrderStatusEnum;
}

/**
 * Check if a given object implements the OrderUpdateDTO interface.
 */
export function instanceOfOrderUpdateDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function OrderUpdateDTOFromJSON(json: any): OrderUpdateDTO {
    return OrderUpdateDTOFromJSONTyped(json, false);
}

export function OrderUpdateDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderUpdateDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'status': !exists(json, 'status') ? undefined : OrderStatusEnumFromJSON(json['status']),
    };
}

export function OrderUpdateDTOToJSON(value?: OrderUpdateDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'status': OrderStatusEnumToJSON(value.status),
    };
}

