/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { OrderDeliveryEnum } from './OrderDeliveryEnum';
import {
    OrderDeliveryEnumFromJSON,
    OrderDeliveryEnumFromJSONTyped,
    OrderDeliveryEnumToJSON,
} from './OrderDeliveryEnum';

/**
 * 
 * @export
 * @interface OrderAddDTO
 */
export interface OrderAddDTO {
    /**
     * 
     * @type {string}
     * @memberof OrderAddDTO
     */
    deliveryAddress?: string | null;
    /**
     * 
     * @type {OrderDeliveryEnum}
     * @memberof OrderAddDTO
     */
    deliveryMethod?: OrderDeliveryEnum;
}

/**
 * Check if a given object implements the OrderAddDTO interface.
 */
export function instanceOfOrderAddDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function OrderAddDTOFromJSON(json: any): OrderAddDTO {
    return OrderAddDTOFromJSONTyped(json, false);
}

export function OrderAddDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderAddDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'deliveryAddress': !exists(json, 'deliveryAddress') ? undefined : json['deliveryAddress'],
        'deliveryMethod': !exists(json, 'deliveryMethod') ? undefined : OrderDeliveryEnumFromJSON(json['deliveryMethod']),
    };
}

export function OrderAddDTOToJSON(value?: OrderAddDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'deliveryAddress': value.deliveryAddress,
        'deliveryMethod': OrderDeliveryEnumToJSON(value.deliveryMethod),
    };
}

