/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const OrderDeliveryEnum = {
    Courier: 'Courier',
    Post: 'Post'
} as const;
export type OrderDeliveryEnum = typeof OrderDeliveryEnum[keyof typeof OrderDeliveryEnum];


export function OrderDeliveryEnumFromJSON(json: any): OrderDeliveryEnum {
    return OrderDeliveryEnumFromJSONTyped(json, false);
}

export function OrderDeliveryEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderDeliveryEnum {
    return json as OrderDeliveryEnum;
}

export function OrderDeliveryEnumToJSON(value?: OrderDeliveryEnum | null): any {
    return value as any;
}

