/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { OrderDeliveryEnum } from './OrderDeliveryEnum';
import {
    OrderDeliveryEnumFromJSON,
    OrderDeliveryEnumFromJSONTyped,
    OrderDeliveryEnumToJSON,
} from './OrderDeliveryEnum';
import type { OrderStatusEnum } from './OrderStatusEnum';
import {
    OrderStatusEnumFromJSON,
    OrderStatusEnumFromJSONTyped,
    OrderStatusEnumToJSON,
} from './OrderStatusEnum';
import type { UserDTO } from './UserDTO';
import {
    UserDTOFromJSON,
    UserDTOFromJSONTyped,
    UserDTOToJSON,
} from './UserDTO';

/**
 * 
 * @export
 * @interface OrderDTO
 */
export interface OrderDTO {
    /**
     * 
     * @type {string}
     * @memberof OrderDTO
     */
    id?: string;
    /**
     * 
     * @type {UserDTO}
     * @memberof OrderDTO
     */
    client?: UserDTO;
    /**
     * 
     * @type {string}
     * @memberof OrderDTO
     */
    deliveryAddress?: string | null;
    /**
     * 
     * @type {number}
     * @memberof OrderDTO
     */
    totalCost?: number;
    /**
     * 
     * @type {number}
     * @memberof OrderDTO
     */
    numberOfItems?: number;
    /**
     * 
     * @type {OrderStatusEnum}
     * @memberof OrderDTO
     */
    status?: OrderStatusEnum;
    /**
     * 
     * @type {OrderDeliveryEnum}
     * @memberof OrderDTO
     */
    deliveryMethod?: OrderDeliveryEnum;
    /**
     * 
     * @type {Date}
     * @memberof OrderDTO
     */
    createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof OrderDTO
     */
    updatedAt?: Date;
}

/**
 * Check if a given object implements the OrderDTO interface.
 */
export function instanceOfOrderDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function OrderDTOFromJSON(json: any): OrderDTO {
    return OrderDTOFromJSONTyped(json, false);
}

export function OrderDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'client': !exists(json, 'client') ? undefined : UserDTOFromJSON(json['client']),
        'deliveryAddress': !exists(json, 'deliveryAddress') ? undefined : json['deliveryAddress'],
        'totalCost': !exists(json, 'totalCost') ? undefined : json['totalCost'],
        'numberOfItems': !exists(json, 'numberOfItems') ? undefined : json['numberOfItems'],
        'status': !exists(json, 'status') ? undefined : OrderStatusEnumFromJSON(json['status']),
        'deliveryMethod': !exists(json, 'deliveryMethod') ? undefined : OrderDeliveryEnumFromJSON(json['deliveryMethod']),
        'createdAt': !exists(json, 'createdAt') ? undefined : (new Date(json['createdAt'])),
        'updatedAt': !exists(json, 'updatedAt') ? undefined : (new Date(json['updatedAt'])),
    };
}

export function OrderDTOToJSON(value?: OrderDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'client': UserDTOToJSON(value.client),
        'deliveryAddress': value.deliveryAddress,
        'totalCost': value.totalCost,
        'numberOfItems': value.numberOfItems,
        'status': OrderStatusEnumToJSON(value.status),
        'deliveryMethod': OrderDeliveryEnumToJSON(value.deliveryMethod),
        'createdAt': value.createdAt === undefined ? undefined : (value.createdAt.toISOString()),
        'updatedAt': value.updatedAt === undefined ? undefined : (value.updatedAt.toISOString()),
    };
}

