/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ProductTypeEnum } from './ProductTypeEnum';
import {
    ProductTypeEnumFromJSON,
    ProductTypeEnumFromJSONTyped,
    ProductTypeEnumToJSON,
} from './ProductTypeEnum';

/**
 * 
 * @export
 * @interface ProductUpdateDTO
 */
export interface ProductUpdateDTO {
    /**
     * 
     * @type {string}
     * @memberof ProductUpdateDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ProductUpdateDTO
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProductUpdateDTO
     */
    description?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ProductUpdateDTO
     */
    price?: number;
    /**
     * 
     * @type {ProductTypeEnum}
     * @memberof ProductUpdateDTO
     */
    productType?: ProductTypeEnum;
}

/**
 * Check if a given object implements the ProductUpdateDTO interface.
 */
export function instanceOfProductUpdateDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ProductUpdateDTOFromJSON(json: any): ProductUpdateDTO {
    return ProductUpdateDTOFromJSONTyped(json, false);
}

export function ProductUpdateDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductUpdateDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'price': !exists(json, 'price') ? undefined : json['price'],
        'productType': !exists(json, 'productType') ? undefined : ProductTypeEnumFromJSON(json['productType']),
    };
}

export function ProductUpdateDTOToJSON(value?: ProductUpdateDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'description': value.description,
        'price': value.price,
        'productType': ProductTypeEnumToJSON(value.productType),
    };
}

