/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';
import type { ShoppingCartDTOPagedResponse } from './ShoppingCartDTOPagedResponse';
import {
    ShoppingCartDTOPagedResponseFromJSON,
    ShoppingCartDTOPagedResponseFromJSONTyped,
    ShoppingCartDTOPagedResponseToJSON,
} from './ShoppingCartDTOPagedResponse';

/**
 * 
 * @export
 * @interface ShoppingCartDTOPagedResponseRequestResponse
 */
export interface ShoppingCartDTOPagedResponseRequestResponse {
    /**
     * 
     * @type {ShoppingCartDTOPagedResponse}
     * @memberof ShoppingCartDTOPagedResponseRequestResponse
     */
    response?: ShoppingCartDTOPagedResponse;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof ShoppingCartDTOPagedResponseRequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the ShoppingCartDTOPagedResponseRequestResponse interface.
 */
export function instanceOfShoppingCartDTOPagedResponseRequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ShoppingCartDTOPagedResponseRequestResponseFromJSON(json: any): ShoppingCartDTOPagedResponseRequestResponse {
    return ShoppingCartDTOPagedResponseRequestResponseFromJSONTyped(json, false);
}

export function ShoppingCartDTOPagedResponseRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShoppingCartDTOPagedResponseRequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : ShoppingCartDTOPagedResponseFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function ShoppingCartDTOPagedResponseRequestResponseToJSON(value?: ShoppingCartDTOPagedResponseRequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': ShoppingCartDTOPagedResponseToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

