/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ShoppingCartDTO } from './ShoppingCartDTO';
import {
    ShoppingCartDTOFromJSON,
    ShoppingCartDTOFromJSONTyped,
    ShoppingCartDTOToJSON,
} from './ShoppingCartDTO';

/**
 * 
 * @export
 * @interface ShoppingCartDTOPagedResponse
 */
export interface ShoppingCartDTOPagedResponse {
    /**
     * 
     * @type {number}
     * @memberof ShoppingCartDTOPagedResponse
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof ShoppingCartDTOPagedResponse
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof ShoppingCartDTOPagedResponse
     */
    totalCount?: number;
    /**
     * 
     * @type {Array<ShoppingCartDTO>}
     * @memberof ShoppingCartDTOPagedResponse
     */
    data?: Array<ShoppingCartDTO> | null;
}

/**
 * Check if a given object implements the ShoppingCartDTOPagedResponse interface.
 */
export function instanceOfShoppingCartDTOPagedResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ShoppingCartDTOPagedResponseFromJSON(json: any): ShoppingCartDTOPagedResponse {
    return ShoppingCartDTOPagedResponseFromJSONTyped(json, false);
}

export function ShoppingCartDTOPagedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShoppingCartDTOPagedResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'page': !exists(json, 'page') ? undefined : json['page'],
        'pageSize': !exists(json, 'pageSize') ? undefined : json['pageSize'],
        'totalCount': !exists(json, 'totalCount') ? undefined : json['totalCount'],
        'data': !exists(json, 'data') ? undefined : (json['data'] === null ? null : (json['data'] as Array<any>).map(ShoppingCartDTOFromJSON)),
    };
}

export function ShoppingCartDTOPagedResponseToJSON(value?: ShoppingCartDTOPagedResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'page': value.page,
        'pageSize': value.pageSize,
        'totalCount': value.totalCount,
        'data': value.data === undefined ? undefined : (value.data === null ? null : (value.data as Array<any>).map(ShoppingCartDTOToJSON)),
    };
}

