/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';
import type { ShoppingCartDTO } from './ShoppingCartDTO';
import {
    ShoppingCartDTOFromJSON,
    ShoppingCartDTOFromJSONTyped,
    ShoppingCartDTOToJSON,
} from './ShoppingCartDTO';

/**
 * 
 * @export
 * @interface ShoppingCartDTORequestResponse
 */
export interface ShoppingCartDTORequestResponse {
    /**
     * 
     * @type {ShoppingCartDTO}
     * @memberof ShoppingCartDTORequestResponse
     */
    response?: ShoppingCartDTO;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof ShoppingCartDTORequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the ShoppingCartDTORequestResponse interface.
 */
export function instanceOfShoppingCartDTORequestResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ShoppingCartDTORequestResponseFromJSON(json: any): ShoppingCartDTORequestResponse {
    return ShoppingCartDTORequestResponseFromJSONTyped(json, false);
}

export function ShoppingCartDTORequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShoppingCartDTORequestResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'response': !exists(json, 'response') ? undefined : ShoppingCartDTOFromJSON(json['response']),
        'errorMessage': !exists(json, 'errorMessage') ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function ShoppingCartDTORequestResponseToJSON(value?: ShoppingCartDTORequestResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'response': ShoppingCartDTOToJSON(value.response),
        'errorMessage': ErrorMessageToJSON(value.errorMessage),
    };
}

